name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build nest-better-auth

      - name: validate npm token is set, use string length to check
        run: echo ${{ secrets.NPM_TOKEN }} | wc -c
        run: echo "NPM_TOKEN is not set"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} 

      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release 

      - name: Debug whoami
        if: failure()
        run: npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} 
